# Generated by Django 3.2.3 on 2021-07-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_quiz_lecture_na'),
        ('questions', '0002_auto_20210724_1207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizAnswer',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='QuizQuestion',
            new_name='Question',
        ),
    ]
