# Generated by Django 3.2.4 on 2021-06-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='result',
            name='learner',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
