# Generated by Django 3.2.4 on 2021-06-28 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20210628_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='results',
            name='learner',
        ),
        migrations.AddField(
            model_name='assessment',
            name='learner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
