# Generated by Django 3.2.3 on 2021-07-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_result_study_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='difficulty',
            new_name='difficulty_status',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='number_of_questions',
            new_name='questions_number',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='required_score_to_pass',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='topic',
        ),
        migrations.AddField(
            model_name='quiz',
            name='pass_score',
            field=models.IntegerField(help_text='Score in %', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_time',
            field=models.IntegerField(help_text='Time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
