# Generated by Django 3.2.4 on 2021-06-06 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import syllabus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnames', to='syllabus.level')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(max_length=100, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('chapter', models.PositiveSmallIntegerField(verbose_name='Chapter')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('lecture_video', models.FileField(blank=True, null=True, upload_to=syllabus.models.files_save, verbose_name='Video')),
                ('lecture_presentations', models.FileField(blank=True, upload_to=syllabus.models.files_save, verbose_name='Presentations')),
                ('lecture_notes', models.FileField(blank=True, upload_to=syllabus.models.files_save, verbose_name='Notes')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.level')),
                ('subname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='syllabus.subname')),
                ('user_created_lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['chapter'],
            },
        ),
    ]
