# Generated by Django 3.2.4 on 2021-06-08 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(blank=True, max_length=100)),
                ('question_body', models.TextField(max_length=500)),
                ('question_date', models.DateTimeField(auto_now_add=True)),
                ('lecture_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='syllabus.lecture')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-question_date'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_body', models.TextField(max_length=500)),
                ('answer_date', models.DateTimeField(auto_now_add=True)),
                ('q_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='syllabus.question')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
