# Generated by Django 3.2.4 on 2021-06-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_assessment_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='result',
            name='learner',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
