# Generated by Django 3.2.4 on 2021-06-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_quizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizes',
            name='lecture_n',
        ),
        migrations.AddField(
            model_name='quizes',
            name='lecture',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='syllabus.lecture'),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
