# Generated by Django 3.2.4 on 2021-06-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_auto_20210616_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizes',
            options={'ordering': ['question']},
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='date',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='mark',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.quizes')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=200)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.result')),
            ],
        ),
    ]
