# Generated by Django 3.2.4 on 2021-06-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_auto_20210617_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_notes',
        ),
    ]
