# Generated by Django 3.2.4 on 2021-07-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_lecturegoals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizes',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='result',
            name='quizes',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='Quizes',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
