# Generated by Django 3.2.3 on 2021-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0010_auto_20210705_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_body',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_body',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='subname',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='subname',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='subname',
            name='subname_id',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
