# Generated by Django 3.2.3 on 2021-08-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0011_auto_20210728_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subname',
            name='level',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='level',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='subname',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Subname',
        ),
    ]
