# Generated by Django 3.2.4 on 2021-06-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_auto_20210617_1019'),
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='lecture_na',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qs', to='syllabus.lecture'),
        ),
    ]
