# Generated by Django 3.2.3 on 2021-07-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_quiz_lecture_na'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='difficulty',
            new_name='difficulty_status',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='required_score_to_pass',
            new_name='pass_score',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='number_of_questions',
            new_name='questions_number',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='quiz_name',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='time',
            new_name='quiz_time',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='topic',
            new_name='quiz_title',
        ),
    ]
