# Generated by Django 3.2.3 on 2021-07-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_result_study_plan'),
        ('assess_questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='quiz_question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='created',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created',
            new_name='time_created',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_title',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='user_quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
